Updating e2etest runner for verbose output.
- Didn't help solve my problem, but thought it would be useful
  long-term anyway.
- Having trouble with protractor and chrome not talking.
- Error is:
    /home/CS/users/jsouthwo/.linux/Documents/472_cos/npm/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
    var template = new Error(this.message);
    UnknownError: The process has not exited yet therefore no result is available ...
- Problem is likely due to incompatible version of Chrome, but you can't
  go back and get old versions, so I think I'm stuck.

[skip ci]